
// Type: Core.models.enums.missions.MISSION_TYPE
// Assembly: Core, Version=0.0.0.1, Culture=neutral, PublicKeyToken=null
// MVID: 263E2FBF-1098-4552-8FB3-F6A660503737
// Interprise: C:\Users\Cuzin\3,50Core.dll

namespace Core.models.enums.missions
{
  public enum MISSION_TYPE
  {
    NA,
    C4_PLANT,
    C4_DEFUSE,
    HIT_HEAD_20,
    HIT_HEAD_30,
    HIT_CHEST_20,
    HIT_CHEST_30,
    HIT_ARM_20,
    HIT_ARM_30,
    HIT_LEG_20,
    HIT_LEG_30,
    STAGE_ENTER,
    STAGE_INTERCEPT,
    WIN,
    DEFEAT,
    KILL,
    DEATH,
    SUICIDE,
    ENFORCE_EXIT,
    RANK_1,
    RANK_2,
    RANK_3,
    RANK_4,
    RANK_5,
    RANK_6,
    RANK_7,
    RANK_8,
    HEADSHOT,
    DOUBLE_KILL,
    PIERCING,
    TRIPLE_KILL,
    MASS_KILL,
    HIT_RATE_40,
    HIT_RATE_50,
    HIT_RATE_60,
    KILL_RATE_40,
    KILL_RATE_50,
    KILL_RATE_60,
    HELMET_PROTECTION,
    DESTROY,
    KILL_WEAPONCLASS,
    DOUBLE_KILL_WEAPONCLASS,
    TRIPLE_KILL_WEAPONCLASS,
    USE_WEAPON,
    CHAINKILLER,
    CHAINSLUGGER,
    CHAINSTOPPER,
    CHAINHEADSHOT,
    PROTECT,
    DEATHBLOW,
    TOUCHDOWN,
    TOUCHDOWN_ACE_ATTACKER,
    TOUCHDOWN_HATTRICK,
    TOUCHDOWN_GAME_MAKER,
    KILL_ASSIST,
    KILL_MAN,
  }
}
